# Generated by Django 3.2.16 on 2023-01-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='default-movie.jpg', upload_to=''),
        ),
    ]
