# Generated by Django 3.2.17 on 2023-03-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='director',
            field=models.TextField(default='Undefined'),
        ),
        migrations.AddField(
            model_name='article',
            name='protagonist',
            field=models.TextField(default='Undefined'),
        ),
    ]
